server:
  port: 1398


spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  # 日期返回格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    enabled: false
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: -1ms
    connect-timeout: 30000ms

  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/ftm-system?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
          hikari:
            max-lifetime: 60000
        slave_1:
          url: jdbc:mysql://127.0.0.1:3306/job
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
          hikari:
            max-lifetime: 60000
#        db2:  #oracle
#          url: jdbc:oracle:thin:@//xxxx:1521/ncdb
#          username: xxx
#          password: xxx
#          driver-class-name: oracle.jdbc.OracleDriver

#        db2:
#          jdbc-url: jdbc:postgresql://ip地址:端口/数据库名?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#          username: 数据库账号
#          password: 数据库密码
#          driver-class-name: org.postgresql.Driver
#        db3:
#          jdbc-url: jdbc:sqlserver://ip地址:端口;databaseName=数据库名
#          username: 数据库账号
#          password: 数据库密码
#          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        #......省略
        #以上会配置一个默认库master，一个组slave下有两个子库slave_1,slave_2
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/ftm-system?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
#    username: root
#    password: root

  quartz:
    #quartz定时任务,采用数据库方式
    job-store-type: jdbc
    initialize-schema: never   # 注意:initialize-schema: never,这个属性，第一次生成quartz内置表时设置为always,生成后改为never，不然每次启动系统都会重新生成表。
    #定时任务启动开关，true-开  false-关
    auto-startup: false
    #延迟1秒启动定时任务
    startup-delay: 1s
    #启动时更新己存在的Job
    overwrite-existing-jobs: true
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler
            #ID设置为自动获取 每一个必须不同 (所有调度器实例中是唯一的)
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            #StdJDBCDelegate说明支持集群
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            #quartz内部表的前缀
            tablePrefix: QRTZ_
            #是否加入集群
            isClustered: false
            #容许的最大作业延长时间
            misfireThreshold: 12000
            #分布式节点有效性检查时间间隔，单位：毫秒
            clusterCheckinInterval: 15000
            #配置是否使用
            useProperties: false
          threadPool:
            #ThreadPool实现的类名
            class: org.quartz.simpl.SimpleThreadPool
            #线程数量
            threadCount: 10
            #线程优先级
            threadPriority: 5
            #配置是否启动自动加载数据库内的定时任务，默认true
            threadsInheritContextClassLoaderOfInitializingThread: true



  rabbitmq:
    enable: false

  data:
    mongodb:
      autoIndexCreation: false
      host: 127.0.0.1
      port: 27017
      database: DataCenter
  #      authentication-database: admin
  #      username: root
  #      password: Ry@Mysq.2021
  shardingsphere:
    datasource:
      names: m1   #配置库的名字，随意
      m1:   #配置目前m1库的数据源信息
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/shop?useUnicode=true
        username: root
        password: 123456
#    sharding:
#      tables:
#        shop:  # 指定shop表的数据分布情况，配置数据节点
#          actualDataNodes: m1.shop_0$->{1..2}
#          tableStrategy:
#            inline:   # 指定shop表的分片策略，分片策略包括分片键和分片算法
#              shardingColumn: id
#              algorithmExpression: shop_0$->{id % 2 + 1}
#          keyGenerator:   # 指定shop表的主键生成策略为SNOWFLAKE
#            type: SNOWFLAKE  #主键生成策略为SNOWFLAKE
#            column: id  #指定主键





##mongodb数据源, 用户名密码、鉴权这些省略，此处演示不配置
mongodb:
  enable: false
  databases:
#    DataCenter: ##这是我自定义的dbname
#      db: ${mongo.DataCenter.db}
#      uri: mongodb://${mongo.DataCenter.host}:${mongo.DataCenter.port}/${mongo.DataCenter.db}
#      username: ${mongo.DataCenter.username:}
#      password: ${mongo.DataCenter.password:}
#      authenticationDatabase: ${mongo.DataCenter.authenticationDatabase:}
    LogDB:
      db: ${mongo.LogDB.db}
      uri: mongodb://${mongo.LogDB.host}:${mongo.LogDB.port}/${mongo.LogDB.db}
      username: ${mongo.LogDB.username:}
      password: ${mongo.LogDB.password:}
      authenticationDatabase: ${mongo.LogDB.authenticationDatabase:}


mongo:
#  DataCenter:
#    db: TempTest
#    host: 192.168.200.125
#    port: 25002
  LogDB:
    db: YJLogDB
    host: 192.168.200.125
    port: 25002

mybatis-plus:
  type-aliases-package: top.anets.modules.**.entity
  # xxxMapper.xml 路径
  mapper-locations: classpath*:top/anets/modules/**/mapper/**/*.xml

file:
  ROOT_PATH: C:\Users\Administrator\Desktop\temp\imgs

#日志
logging:
  config: classpath:logback-spring.xml


xxl:
  job:
    admin:
      # xxl-job后台管理界面的地址
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      # 此执行器的名称
      appname: design
      # 此执行器的端口
      port: 38801
      # 此执行器的日志存放路径
      logpath: logs/xxl-job/design
      # 此执行器的日志保存时间
      logretentiondays: 7
    accessToken: default_token


jetcache:
  # 统计间隔，0表示不统计，开启后定期在控制台输出缓存信息
  statIntervalMinutes: 15
  # 是否把cacheName作为远程缓存key前缀
  areaInCacheName: false
  # 本地缓存配置
  local:
    default: # default表示全部生效，也可以指定某个cacheName
      # 本地缓存类型，其他可选：caffeine/linkedhashmap
      type: linkedhashmap
      keyConvertor: fastjson
  # 远程缓存配置
  remote:
    default: # default表示全部生效，也可以指定某个cacheName
      type: redis
      # key转换器方式n
      keyConvertor: fastjson
      broadcastChannel: projectA
      # redis序列化方式
      valueEncoder: java
      valueDecoder: java
      # redis线程池
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      # redis地址与端口
      host: 127.0.0.1
      port: 6379


