server:
  port: 1398


spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  # 日期返回格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: -1ms
    connect-timeout: 30000ms

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ftm-system?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: tyb

  rabbitmq:
    enable: false


mybatis-plus:
  type-aliases-package: top.anets.modules.**.entity
  # xxxMapper.xml 路径
  mapper-locations: classpath*:top/anets/modules/**/mapper/**/*.xml

file:
  ROOT_PATH: C:\Users\Administrator\Desktop\temp\imgs


#日志
logging:
  config: classpath:logback-spring.xml


xxl:
  job:
    admin:
      # xxl-job后台管理界面的地址
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      # 此执行器的名称
      appname: design
      # 此执行器的端口
      port: 38801
      # 此执行器的日志存放路径
      logpath: logs/xxl-job/design
      # 此执行器的日志保存时间
      logretentiondays: 7
    accessToken: default_token